apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: weather-app
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  WEATHER_API_URL: {{ .Values.config.weatherApiUrl | quote }}
  API_URL: "http://weather-api:{{ .Values.api.port }}"
