apiVersion: v1
kind: Service
metadata:
  name: weather-app-api
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: weather-app
    component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      nodePort: {{ .Values.api.service.nodePort }}
